# Generated by Django 2.2.6 on 2019-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
